#version 460
#include "hurdygurdy.glsl"

layout(push_constant) uniform Push {
    uint bufIdx;
    uint imgIdx;
} push;

layout(HgStorageBuffer) buffer DataBuf { uint data[]; } bufs[];
layout(HgStorageImage, rgba8) uniform writeonly image2D img[];

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    uint idx = coord.y * int(gl_NumWorkGroups.x) + coord.x;
    uint val = bufs[push.bufIdx].data[idx];
    imageStore(img[push.imgIdx], coord,
        vec4(
            float(val & 0xFFu) / 255.0,
            float((val >> 8) & 0xFFu) / 255.0,
            float((val >> 16) & 0xFFu) / 255.0,
            float((val >> 24) & 0xFFu) / 255.0));
}
