#version 460

#include "hurdygurdy.glsl"

layout(push_constant) uniform Push {
    uint srcIdx;
    uint dstIdx;
} push;

layout(HgCombinedImageSampler) uniform sampler2D srcImg[];
layout(HgStorageImage, rgba8) uniform writeonly image2D dstImg[];

void main()
{
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec4 sum = vec4(0.0);
    for (int dy = -1; dy <= 1; ++dy)
        for (int dx = -1; dx <= 1; ++dx)
            sum += texelFetch(srcImg[push.srcIdx], coord + ivec2(dx, dy), 0);
    imageStore(dstImg[push.dstIdx], coord, sum / 9.0);
}
